name: Daily Commit

on:
  schedule:
    - cron: '0 22 * * *' # Runs every day at midnight UTC
  push:
    branches:
      - main

jobs:
  daily-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository content
        uses: actions/checkout@v2

      - name: Make changes
        run: echo "Daily commit at $(date)" >> daily_commit.txt
