name: Daily Commit

on:
  schedule:
    - cron: '0 22 * * *' # Runs every day at midnight UTC
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  daily-commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository content
        uses: actions/checkout@v2

      - name: 23f2005419@ds.study.iitm.ac.in
        run: echo "Daily commit at $(date)" >> daily_commit.txt

      - name: Commit and push changes
        run: |
          git add .
          git commit -m "Daily commit at $(date)"
          git push

